name: Merge Deployment

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

concurrency:
  group: gh-pages-state
  cancel-in-progress: false

permissions: {}

jobs:
  validate:
    name: Lint & Unit Tests
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Verify syntax, formatting & run unit tests
        run: npm run validate

  deploy:
    needs: [validate]
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Compile JSON to FlatGeobuf
        run: npm run db:convert
      - name: Deploy static content to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@fa24774553152dd7873cd16ebd8d959b010c5445 # v4
        with:
          folder: docs
          branch: gh-pages
          clean: true # Cleanup, but leave PR deployments
          clean-exclude: deployments
