name: Merge Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'

concurrency:
  group: deploy-production
  cancel-in-progress: true

permissions: {}

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Deploy static content to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages
          clean: true # Cleanup, but leave PR deployments
          clean-exclude: deployments
